export const PROJECTS = [
  { id:1, name:'Amazon Rainforest Protection', type:'forest', emoji:'🌳',
    bg:'linear-gradient(135deg,#1a3d1f,#0d2818)',
    desc:'Protect 50,000 hectares of primary Amazon rainforest from deforestation in Brazil.',
    co2:'1,000 kg CO₂ per credit', priceEth:0.025, priceUsd:60,
    badge:'🔥 Popular', badgeColor:'rgba(249,115,22,.2)', badgeText:'var(--orange)',
    verified:'Gold Standard', country:'🇧🇷 Brazil', available:2450 },
  { id:2, name:'Sahara Solar Energy Farm', type:'solar', emoji:'☀️',
    bg:'linear-gradient(135deg,#3d2e1a,#281d0d)',
    desc:'500MW solar installation replacing coal power for 200,000 homes in Morocco.',
    co2:'800 kg CO₂ per credit', priceEth:0.020, priceUsd:48,
    badge:'⚡ New', badgeColor:'rgba(59,130,246,.2)', badgeText:'var(--blue)',
    verified:'VCS', country:'🇲🇦 Morocco', available:5200 },
  { id:3, name:'Nordic Wind Turbines', type:'wind', emoji:'💨',
    bg:'linear-gradient(135deg,#1a2a3d,#0d1828)',
    desc:'Offshore wind farm generating 300MW clean energy replacing fossil fuels in Norway.',
    co2:'750 kg CO₂ per credit', priceEth:0.018, priceUsd:43,
    badge:'✅ Verified', badgeColor:'rgba(34,197,94,.2)', badgeText:'var(--green)',
    verified:'Gold Standard', country:'🇳🇴 Norway', available:8100 },
  { id:4, name:'Blue Carbon — Mangrove Forest', type:'ocean', emoji:'🌊',
    bg:'linear-gradient(135deg,#1a2e3d,#0d1f2a)',
    desc:'Restore 10,000 ha of mangrove ecosystems in Indonesia, storing carbon in coastal sediments.',
    co2:'1,200 kg CO₂ per credit', priceEth:0.032, priceUsd:76,
    badge:'💎 Premium', badgeColor:'rgba(168,85,247,.2)', badgeText:'var(--purple)',
    verified:'Gold Standard', country:'🇮🇩 Indonesia', available:1200 },
  { id:5, name:'Indian Cookstove Program', type:'other', emoji:'🍳',
    bg:'linear-gradient(135deg,#3d1a1a,#280d0d)',
    desc:'Distribute clean cookstoves to 500,000 households, reducing wood burning and indoor pollution.',
    co2:'600 kg CO₂ per credit', priceEth:0.015, priceUsd:36,
    badge:'🤝 Social', badgeColor:'rgba(236,72,153,.2)', badgeText:'var(--pink)',
    verified:'CDM', country:'🇮🇳 India', available:15000 },
  { id:6, name:'Patagonia Grassland Restoration', type:'forest', emoji:'🌾',
    bg:'linear-gradient(135deg,#1e3a1a,#112610)',
    desc:'Restore 80,000 ha of degraded Patagonian grasslands, enhancing soil carbon sequestration.',
    co2:'900 kg CO₂ per credit', priceEth:0.022, priceUsd:52,
    badge:'🌿 Eco', badgeColor:'rgba(20,184,166,.2)', badgeText:'var(--teal)',
    verified:'VCS', country:'🇦🇷 Argentina', available:3600 },
];
